# Generated by Django 2.2.5 on 2019-09-18 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0014_auto_20190918_0852'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date']},
        ),
    ]
